import { useEffect, useMemo, useState } from "react";
import { useNavigate } from "react-router-dom";
import { createBill, getStores } from "../../services/billingService";
import "../../styles/Billing.css";

const blankItem = { product_name:"", quantity:1, rate:0, discount:0 };
export default function BillingEntry(){
 const navigate=useNavigate(); const [stores,setStores]=useState([]); const [form,setForm]=useState({bill_no:"",store_id:"",customer_name:"",bill_date:new Date().toISOString().slice(0,16),discount:0,tax:0,payment_type:"Cash",transaction_reference:""}); const [items,setItems]=useState([{...blankItem}]); const [saving,setSaving]=useState(false); const [message,setMessage]=useState("");
 useEffect(()=>{getStores().then(r=>setStores(r.data?.data||[])).catch(()=>{});},[]);
 const subtotal=useMemo(()=>items.reduce((s,i)=>s+(Number(i.quantity)||0)*(Number(i.rate)||0),0),[items]); const grandTotal=Math.max(0,subtotal-Number(form.discount||0)+Number(form.tax||0));
 const updateItem=(index,key,value)=>setItems(a=>a.map((x,i)=>i===index?{...x,[key]:value}:x));
 const submit=async e=>{e.preventDefault();setSaving(true);setMessage(""); try{await createBill({ ...form, subtotal, grand_total:grandTotal, payment_amount:grandTotal, items:items.filter(i=>i.product_name).map(i=>({...i,amount:(Number(i.quantity)||0)*(Number(i.rate)||0)-Number(i.discount||0)})) }); setMessage("Bill created successfully."); setTimeout(()=>navigate("/billing/bills"),600);}catch(err){setMessage(err.response?.data?.message||"Failed to create bill.");}finally{setSaving(false);}};
 return <div className="billing-page"><div className="billing-header"><div><h1>Billing Entry</h1><p>Create a new customer bill and payment record.</p></div></div><form className="billing-card" onSubmit={submit}><div className="billing-grid"><label>Bill No<input required value={form.bill_no} onChange={e=>setForm({...form,bill_no:e.target.value})}/></label><label>Store<select required value={form.store_id} onChange={e=>setForm({...form,store_id:e.target.value})}><option value="">Select store</option>{stores.map(s=><option key={s.id} value={s.id}>{s.store_name}</option>)}</select></label><label>Customer Name<input value={form.customer_name} onChange={e=>setForm({...form,customer_name:e.target.value})}/></label><label>Bill Date<input type="datetime-local" value={form.bill_date} onChange={e=>setForm({...form,bill_date:e.target.value})}/></label></div><div className="billing-section"><div className="billing-section-title"><h3>Bill Items</h3><button type="button" className="billing-secondary" onClick={()=>setItems([...items,{...blankItem}])}>+ Add Item</button></div>{items.map((item,index)=><div className="billing-item-row" key={index}><input placeholder="Product / Service" value={item.product_name} onChange={e=>updateItem(index,"product_name",e.target.value)}/><input type="number" min="0" step="0.001" placeholder="Qty" value={item.quantity} onChange={e=>updateItem(index,"quantity",e.target.value)}/><input type="number" min="0" step="0.01" placeholder="Rate" value={item.rate} onChange={e=>updateItem(index,"rate",e.target.value)}/><span>₹{((Number(item.quantity)||0)*(Number(item.rate)||0)).toFixed(2)}</span>{items.length>1&&<button type="button" className="billing-icon-button" onClick={()=>setItems(items.filter((_,i)=>i!==index))}>×</button>}</div>)}</div><div className="billing-grid"><label>Discount<input type="number" min="0" step="0.01" value={form.discount} onChange={e=>setForm({...form,discount:e.target.value})}/></label><label>Tax<input type="number" min="0" step="0.01" value={form.tax} onChange={e=>setForm({...form,tax:e.target.value})}/></label><label>Payment Type<select value={form.payment_type} onChange={e=>setForm({...form,payment_type:e.target.value})}>{["Cash","UPI","Card","Bank Transfer","Other"].map(x=><option key={x}>{x}</option>)}</select></label><label>Transaction Reference<input value={form.transaction_reference} onChange={e=>setForm({...form,transaction_reference:e.target.value})}/></label></div><div className="billing-total">Grand Total <strong>₹{grandTotal.toFixed(2)}</strong></div>{message&&<div className="billing-message">{message}</div>}<div className="billing-actions"><button type="button" className="billing-secondary" onClick={()=>navigate("/billing/bills")}>Cancel</button><button disabled={saving} className="billing-primary">{saving?"Saving...":"Create Bill"}</button></div></form></div>;
}
