import {useEffect,useMemo,useState} from "react";
import {FaCloudUploadAlt,FaDownload,FaEye,FaPlus,FaSearch,FaTrash,FaDatabase,FaTimes,FaFileCsv} from "react-icons/fa";
import ProfessionalModal from "../../components/common/ProfessionalModal";import BulkUploadModal from "../../components/common/BulkUploadModal";import ConfirmDialog from "../../components/common/ConfirmDialog";import Pagination from "../../components/common/Pagination";
import {getInventoryOptions,getErpSales,getErpSaleById,createErpSale,deleteErpSale,deleteAllErpSales,exportErpSales,bulkUploadErpSales} from "../../services/inventoryPlanningService";import "../../styles/pages/InventoryPlanning.css";
const MONTHS=["January","February","March","April","May","June","July","August","September","October","November","December"];
const perms=()=>{let u={},p={};try{u=JSON.parse(localStorage.getItem("user")||"{}")}catch{}try{p=JSON.parse(localStorage.getItem("permissions")||"{}")}catch{}const a=[true,1,"1"].includes(u?.administrator)||[true,1,"1"].includes(u?.is_admin),x=p?.["Inventory Planning"]||"None";return{view:a||["View","Add","Edit","Full"].includes(x),add:a||["Add","Edit","Full"].includes(x),del:a||x==="Full"};};
const csv=v=>`"${String(v??"").replace(/"/g,'""')}"`;
export default function ERPDataUpload(){const pr=useMemo(perms,[]),[rows,setRows]=useState([]),[stores,setStores]=useState([]),[cats,setCats]=useState([]),[years,setYears]=useState([]),[search,setSearch]=useState(""),[store,setStore]=useState(""),[year,setYear]=useState(""),[category,setCategory]=useState(""),[page,setPage]=useState(1),[size,setSize]=useState(10),[total,setTotal]=useState(0),[loading,setLoading]=useState(true),[error,setError]=useState(""),[bulk,setBulk]=useState(false),[add,setAdd]=useState(false),[view,setView]=useState(null),[del,setDel]=useState(null),[delAll,setDelAll]=useState(false),[form,setForm]=useState({store_id:"",store_name:"",sale_year:new Date().getFullYear()-1,sale_month:"August",category:"",sales_amount:"",units_sold:"",discount_percent:""});
 const options=async()=>{try{const r=await getInventoryOptions();if(r.success){setStores(r.data?.stores||[]);setCats(r.data?.categories||[]);setYears(r.data?.years||[]);}}catch(e){}};
 const load=async()=>{setLoading(true);try{const r=await getErpSales({page,pageSize:size,search,store,year,category});setRows(r.data||[]);setTotal(Number(r.pagination?.total||0));setError("");}catch(e){setError(e.response?.data?.message||"Unable to load ERP historical sales data.")}finally{setLoading(false)}};
 useEffect(()=>{options()},[]);useEffect(()=>{load()},[page,size,search,store,year,category]);
 const reset=()=>{setSearch("");setStore("");setYear("");setCategory("");setPage(1)};
 const exportCsv=async()=>{try{const r=await exportErpSales(),d=r.data||[];if(!d.length)return alert("No ERP historical data available to export.");const h=["Store Name","Year","Month","Category","Sales Amount","Units Sold","Discount %"];const c=[h.join(","),...d.map(x=>[x.store_name,x.sale_year,x.sale_month,x.category,x.sales_amount,x.units_sold,x.discount_percent].map(csv).join(","))].join("\n");const u=URL.createObjectURL(new Blob([c],{type:"text/csv"})),a=document.createElement("a");a.href=u;a.download="MIARCUS_ERP_Historical_Sales.csv";a.click();URL.revokeObjectURL(u)}catch(e){alert(e.response?.data?.message||"Export failed.")}};
 const submit=async e=>{e.preventDefault();try{const r=await createErpSale(form);if(r.success){setAdd(false);options();load()}}catch(e){alert(e.response?.data?.message||"Unable to add ERP sales record.")}};
 const remove=async()=>{try{await deleteErpSale(del);load()}catch(e){alert(e.response?.data?.message||"Delete failed.")}finally{setDel(null)}};
 const removeAll=async()=>{try{await deleteAllErpSales();load();options();alert("All ERP historical sales data deleted successfully.")}catch(e){alert(e.response?.data?.message||"Delete all failed.")}finally{setDelAll(false)}};
 if(!pr.view)return <div className="inventory-page"><div className="inventory-empty-permission">You do not have permission to view Inventory Planning.</div></div>;
 return <div className="inventory-page"><div className="inventory-shell"><div className="inventory-hero"><div><div className="inventory-eyebrow"><FaDatabase/> INVENTORY PLANNING</div><h1>ERP Data Import</h1><p>Import historical sales data once and use it as the planning foundation for store-level inventory decisions.</p></div><div className="inventory-hero-badge"><FaFileCsv/><span>Historical Sales</span></div></div>
 <section className="inventory-card inventory-upload-card"><div className="inventory-card-heading"><div><span className="inventory-step">01</span><div><h2>Upload Historical Sales Data</h2><p>CSV, XLSX or XLS. Required: Store Name, Year, Month, Category, Sales, Units.</p></div></div><button className="inventory-btn inventory-btn-primary" disabled={!pr.add} onClick={()=>setBulk(true)}><FaCloudUploadAlt/> Bulk Upload</button></div><div className="inventory-upload-tip"><FaDownload/><strong>Recommended columns:</strong> Store Name · Year · Month · Category · Sales · Units · Discount %</div></section>
 <section className="inventory-card"><div className="inventory-section-top"><div><span className="inventory-eyebrow">GLOBAL DATA</span><h2>Uploaded Data History <span>({total} records)</span></h2><p>Search, inspect and safely remove historical records.</p></div><div className="inventory-toolbar-actions">{pr.add&&<button className="inventory-btn inventory-btn-secondary" onClick={()=>setAdd(true)}><FaPlus/> Add Entry</button>}<button className="inventory-btn inventory-btn-secondary" onClick={exportCsv}><FaDownload/> Export CSV</button>{pr.del&&<button className="inventory-btn inventory-btn-danger" onClick={()=>setDelAll(true)}><FaTrash/> Delete All</button>}</div></div>
 <div className="inventory-filter-grid"><label className="inventory-search"><FaSearch/><input value={search} onChange={e=>{setSearch(e.target.value);setPage(1)}} placeholder="Search store or category..."/></label><select value={store} onChange={e=>{setStore(e.target.value);setPage(1)}}><option value="">All stores</option>{stores.map(s=><option key={s.id} value={s.store_name}>{s.store_name}</option>)}</select><select value={year} onChange={e=>{setYear(e.target.value);setPage(1)}}><option value="">All years</option>{years.map(y=><option key={y} value={y}>{y}</option>)}</select><select value={category} onChange={e=>{setCategory(e.target.value);setPage(1)}}><option value="">All categories</option>{cats.map(c=><option key={c} value={c}>{c}</option>)}</select><button className="inventory-clear" onClick={reset}><FaTimes/> Clear</button></div>{error&&<div className="inventory-alert error">{error}</div>}
 <div className="inventory-table-wrap"><table className="inventory-table"><thead><tr><th>STORE</th><th>YEAR</th><th>MONTH</th><th>CATEGORY</th><th>SALES</th><th>UNITS</th><th>DISCOUNT</th><th>CREATED</th><th>ACTIONS</th></tr></thead><tbody>{loading?<tr><td colSpan="9" className="inventory-table-state">Loading data...</td></tr>:rows.length===0?<tr><td colSpan="9" className="inventory-table-state"><div className="inventory-empty-icon"><FaDatabase/></div><strong>No historical sales found</strong><span>Upload your first ERP dataset to begin planning.</span></td></tr>:rows.map(r=><tr key={r.id}><td><strong>{r.store_name}</strong></td><td>{r.sale_year}</td><td>{r.sale_month}</td><td>{r.category}</td><td>₹{Number(r.sales_amount||0).toLocaleString("en-IN")}</td><td>{Number(r.units_sold||0).toLocaleString("en-IN")}</td><td>{Number(r.discount_percent||0).toFixed(1)}%</td><td>{r.created_at?new Date(r.created_at).toLocaleDateString("en-IN"):"-"}</td><td><div className="inventory-row-actions"><button className="inventory-icon-btn view" title="View" onClick={async()=>{try{setView((await getErpSaleById(r.id)).data)}catch(e){alert(e.response?.data?.message||"Unable to view record.")}}}><FaEye/></button>{pr.del&&<button className="inventory-icon-btn delete" title="Delete" onClick={()=>setDel(r.id)}><FaTrash/></button>}</div></td></tr>)}</tbody></table></div><Pagination currentPage={page} totalPages={Math.max(1,Math.ceil(total/size))} totalRecords={total} pageSize={size} onPageChange={setPage} onPageSizeChange={v=>{setSize(v);setPage(1)}}/></section></div>
 <BulkUploadModal isOpen={bulk} onClose={()=>setBulk(false)} uploadFunction={bulkUploadErpSales} onSuccess={()=>{load();options()}} title="Import Historical Sales" acceptedFile=".csv,.xlsx,.xls"/>
 <ProfessionalModal isOpen={add} onClose={()=>setAdd(false)} title="Add ERP Sales Entry" subtitle="Create one historical sales record manually." icon="+" size="large" footer={<><button className="inventory-modal-btn secondary" onClick={()=>setAdd(false)}>Cancel</button><button className="inventory-modal-btn primary" type="submit" form="erp-sale-form">Save Entry</button></>}><form id="erp-sale-form" className="inventory-form" onSubmit={submit}><div className="inventory-form-grid"><label>Store <span>*</span><select value={form.store_id} onChange={e=>{const s=stores.find(x=>String(x.id)===e.target.value);setForm({...form,store_id:e.target.value,store_name:s?.store_name||""})}} required><option value="">Select store</option>{stores.map(s=><option key={s.id} value={s.id}>{s.store_name}</option>)}</select></label><label>Category <span>*</span><input value={form.category} onChange={e=>setForm({...form,category:e.target.value})} list="erp-cats" required/><datalist id="erp-cats">{cats.map(c=><option key={c} value={c}/>)}</datalist></label><label>Year <span>*</span><input type="number" value={form.sale_year} onChange={e=>setForm({...form,sale_year:e.target.value})} required/></label><label>Month <span>*</span><select value={form.sale_month} onChange={e=>setForm({...form,sale_month:e.target.value})}>{MONTHS.map(m=><option key={m}>{m}</option>)}</select></label><label>Sales Amount <span>*</span><input type="number" min="0" step="0.01" value={form.sales_amount} onChange={e=>setForm({...form,sales_amount:e.target.value})} required/></label><label>Units Sold <span>*</span><input type="number" min="0" step="1" value={form.units_sold} onChange={e=>setForm({...form,units_sold:e.target.value})} required/></label><label>Discount %<input type="number" min="0" max="100" step="0.1" value={form.discount_percent} onChange={e=>setForm({...form,discount_percent:e.target.value})}/></label></div></form></ProfessionalModal>
 <ProfessionalModal isOpen={!!view} onClose={()=>setView(null)} title="ERP Sales Record" subtitle="Read-only global data view." icon="◉" footer={<button className="inventory-modal-btn secondary" onClick={()=>setView(null)}>Close</button>}>{view&&<div className="inventory-detail-grid">{[["Store",view.store_name],["Year",view.sale_year],["Month",view.sale_month],["Category",view.category],["Sales Amount",`₹${Number(view.sales_amount||0).toLocaleString("en-IN")}`],["Units Sold",view.units_sold],["Discount",`${Number(view.discount_percent||0).toFixed(1)}%`],["Created",view.created_at?new Date(view.created_at).toLocaleString("en-IN"):"-"]].map(x=><div key={x[0]}><span>{x[0]}</span><strong>{x[1]}</strong></div>)}</div>}</ProfessionalModal>
 <ConfirmDialog open={!!del} title="Delete ERP Record" message="This historical sales record will be permanently removed." confirmText="Delete" onConfirm={remove} onCancel={()=>setDel(null)}/><ConfirmDialog open={delAll} title="Delete All Historical Data" message="Every uploaded ERP historical sales record will be permanently deleted. Saved inventory plans will remain." confirmText="Delete All" onConfirm={removeAll} onCancel={()=>setDelAll(false)}/></div>}
