import React from "react";

export default function PrivacyPolicy() {
  return (
    <div
      style={{
        minHeight: "100vh",
        background: "#f5f7fa",
        padding: "40px 20px",
        fontFamily: "Arial, sans-serif",
        color: "#1f2937",
      }}
    >
      <div
        style={{
          maxWidth: "900px",
          margin: "0 auto",
          background: "#ffffff",
          padding: "45px",
          borderRadius: "12px",
          boxShadow: "0 4px 20px rgba(0,0,0,0.08)",
          lineHeight: "1.7",
        }}
      >
        <h1 style={{ color: "#155e75", marginBottom: "8px" }}>
          MIARCUS Privacy Policy
        </h1>

        <p style={{ color: "#6b7280" }}>
          <strong>Last Updated:</strong> September 25, 2026
        </p>

        <p>
          This Privacy Policy explains how MIARCUS ("MIARCUS", "we", "our",
          "us", or "the service") collects, uses, stores, protects, and
          processes information when you use the MIARCUS business management
          platform and its related services.
        </p>

        <h2>1. Information We Collect and Process</h2>

        <p>
          Depending on the features you use, MIARCUS may process information
          such as:
        </p>

        <ul>
          <li>Name and email address</li>
          <li>Employee and user account information</li>
          <li>Business, store, department, and operational information</li>
          <li>Information submitted through MIARCUS forms and modules</li>
          <li>Email notification information required to deliver messages</li>
        </ul>

        <h2>2. Google API and Gmail Data</h2>

        <p>
          MIARCUS uses the Google Gmail API to send system and
          account-related email notifications.
        </p>

        <p>
          MIARCUS uses only the Gmail API permission:
        </p>

        <p>
          <strong>
            https://www.googleapis.com/auth/gmail.send
          </strong>
        </p>

        <p>
          This permission allows MIARCUS to send email messages on behalf of
          the configured MIARCUS notification Gmail account.
        </p>

        <p>
          MIARCUS does <strong>not</strong> use the Gmail integration to read,
          search, download, modify, delete, or manage messages in the Gmail
          inbox. MIARCUS does not access Gmail contacts, drafts, labels,
          attachments, or other Gmail account data through the Gmail API.
        </p>

        <h2>3. Google User Data We Access</h2>

        <p>
          The Gmail integration is limited to the information necessary to
          send email notifications. This may include:
        </p>

        <ul>
          <li>The configured Gmail sender account used to send messages</li>
          <li>Recipient email addresses</li>
          <li>Email subject information</li>
          <li>Email message content generated by MIARCUS</li>
        </ul>

        <p>
          MIARCUS does not use Google user data for advertising, targeted
          advertising, selling data, data brokerage, credit evaluation,
          lending decisions, or any unrelated commercial purpose.
        </p>

        <h2>4. How Google User Data Is Used</h2>

        <p>
          Google user data accessed through the Gmail API is used only to
          provide the email-notification functionality of MIARCUS.
        </p>

        <p>
          The Gmail API integration is used to deliver notifications such as
          system notifications, account-related messages, and other
          application-generated business notifications requested through the
          MIARCUS platform.
        </p>

        <p>
          MIARCUS does not use Google user data to develop, improve, or train
          generalized or non-personalized artificial intelligence or machine
          learning models.
        </p>

        <h2>5. How Google User Data Is Stored</h2>

        <p>
          MIARCUS does not intentionally store the contents of users'
          Gmail inboxes because the application does not request Gmail
          read-access.
        </p>

        <p>
          OAuth credentials, including refresh-token information required for
          the send-only Gmail integration, are stored on secured server
          infrastructure and are not intentionally exposed to ordinary
          MIARCUS users.
        </p>

        <p>
          Email addresses and other information required for normal MIARCUS
          business operations may be stored in the application's database
          according to the application's operational requirements.
        </p>

        <h2>6. Sharing and Disclosure of Google User Data</h2>

        <p>
          MIARCUS does not sell Google user data and does not share Google
          user data with data brokers or advertisers.
        </p>

        <p>
          Information may be processed by service providers that are necessary
          to operate MIARCUS, such as hosting, infrastructure, database, and
          Google API services. Such processing is limited to providing and
          supporting MIARCUS functionality.
        </p>

        <p>
          MIARCUS does not transfer Google user data to third parties for
          advertising, selling, data brokerage, or unrelated purposes.
        </p>

        <h2>7. Data Security</h2>

        <p>
          MIARCUS uses reasonable technical and organizational measures to
          protect information processed by the service.
        </p>

        <p>
          Sensitive authentication credentials and OAuth information are
          stored on secured server infrastructure and are not intentionally
          exposed through the MIARCUS user interface.
        </p>

        <p>
          Access to server-side credentials is restricted to authorized
          systems and personnel where required for operation and maintenance
          of the service.
        </p>

        <h2>8. Data Retention and Deletion</h2>

        <p>
          MIARCUS retains information only for as long as reasonably necessary
          to provide the service, maintain business records, support users,
          maintain system functionality, and comply with applicable legal or
          operational requirements.
        </p>

        <p>
          Gmail API data is not retained beyond what is necessary for the
          email-sending functionality and normal MIARCUS operational records.
          MIARCUS does not retain Gmail inbox contents because it does not
          request Gmail read-access.
        </p>

        <p>
          Where applicable, users or authorized representatives may request
          deletion of information associated with their MIARCUS account,
          subject to legitimate business, security, and legal requirements.
        </p>

        <h2>9. Limited Use of Google Data</h2>

        <p>
          MIARCUS's use of information received from Google APIs will adhere
          to the{" "}
          <strong>Google API Services User Data Policy</strong>, including the
          Limited Use requirements.
        </p>

        <p>
          Google user data is used only to provide or improve the
          user-facing MIARCUS functionality described in this Privacy Policy.
        </p>

        <h2>10. Third-Party Services</h2>

        <p>
          MIARCUS may use third-party services for hosting, infrastructure,
          databases, authentication, email delivery, monitoring, and other
          technical requirements.
        </p>

        <p>
          These services may process information necessary to provide their
          respective functions and are subject to their applicable privacy
          policies and terms.
        </p>

        <h2>11. User Responsibilities</h2>

        <p>
          Users are responsible for providing accurate information and using
          the MIARCUS platform in accordance with applicable laws, company
          policies, and authorized business purposes.
        </p>

        <h2>12. Changes to This Privacy Policy</h2>

        <p>
          MIARCUS may update this Privacy Policy when necessary to reflect
          changes to the service, data practices, security practices, or
          applicable requirements.
        </p>

        <p>
          Updated versions will be published on this page with a revised
          "Last Updated" date.
        </p>

        <h2>13. Contact</h2>

        <p>
          For questions regarding this Privacy Policy, MIARCUS data practices,
          or the Gmail integration, contact:
        </p>

        <p>
          <strong>Email:</strong>{" "}
          <a href="mailto:miarcus.notifications@gmail.com">
            miarcus.notifications@gmail.com
          </a>
        </p>
      </div>
    </div>
  );
}