const express = require("express");
const multer = require("multer");
const fs = require("fs");
const path = require("path");

const router = express.Router();

// ======================================================
// MIDDLEWARE
// ======================================================

const authMiddleware = require(
    "../middleware/authMiddleware"
);

const permissionMiddleware = require(
    "../middleware/permissionMiddleware"
);

const syncGalleryAttachment = require(
    "../middleware/galleryAttachmentSync"
);

// ======================================================
// CONTROLLER
// ======================================================

const controller = require(
    "../controllers/attendanceController"
);

// ======================================================
// ATTENDANCE PHOTO UPLOAD DIRECTORY
// ======================================================

const uploadDir = path.join(
    __dirname,
    "../uploads/attendance"
);

fs.mkdirSync(
    uploadDir,
    {
        recursive: true
    }
);

// ======================================================
// MULTER STORAGE
// ======================================================

const storage = multer.diskStorage({

    destination: (_req, _file, cb) => {
        cb(
            null,
            uploadDir
        );
    },

    filename: (_req, file, cb) => {

        const ext =
            path.extname(
                file.originalname || ".jpg"
            ).toLowerCase() || ".jpg";

        const uniqueName =
            `attendance-${Date.now()}-${Math.random()
                .toString(36)
                .slice(2, 9)}${ext}`;

        cb(
            null,
            uniqueName
        );
    }
});

// ======================================================
// MULTER UPLOAD CONFIGURATION
// ======================================================

const upload = multer({

    storage,

    limits: {
        fileSize: 5 * 1024 * 1024
    },

    fileFilter: (_req, file, cb) => {

        // ------------------------------------------------
        // Only image files are accepted.
        // ------------------------------------------------

        if (
            /^image\/(jpeg|png|webp)$/i.test(
                file.mimetype
            )
        ) {
            return cb(
                null,
                true
            );
        }

        return cb(
            new Error(
                "Only JPG, PNG or WEBP attendance photos are allowed."
            )
        );
    }
});

// ======================================================
// AUTHENTICATION
// ======================================================

router.use(
    authMiddleware
);

// ======================================================
// EMPLOYEE ATTENDANCE WORKSPACE
// ======================================================

// ------------------------------------------------------
// Load employee attendance context
// ------------------------------------------------------

router.get(
    "/context",
    controller.context
);

// ------------------------------------------------------
// Check-in
//
// Photo is automatically captured by the frontend.
// GPS is validated by the controller.
// Store is determined by the backend.
// Timestamp is generated by attendanceModel.
// ------------------------------------------------------

router.post(
    "/check-in",
    upload.single("photo"),
    syncGalleryAttachment("Attendance", "check-in-photo"),
    controller.checkIn
);

// ------------------------------------------------------
// Check-out
//
// A fresh automatic photo is required.
// GPS is validated by the controller.
// Timestamp is generated by attendanceModel.
// ------------------------------------------------------

router.post(
    "/check-out",
    upload.single("photo"),
    syncGalleryAttachment("Attendance", "check-out-photo"),
    controller.checkOut
);

// ======================================================
// ATTENDANCE MANAGEMENT
// ======================================================
//
// Only:
//   Administrator
//   OR
//   Attendance = Full
//
// can access these endpoints.
// ======================================================

// ------------------------------------------------------
// Attendance photo access token
// ------------------------------------------------------

router.get(
    "/photo-token",

    permissionMiddleware(
        "Attendance",
        "Full"
    ),

    controller.photoToken
);

// ------------------------------------------------------
// Reports
// ------------------------------------------------------

router.get(
    "/reports",

    permissionMiddleware(
        "Attendance",
        "Full"
    ),

    controller.reports
);

// ------------------------------------------------------
// Employee filter data
// ------------------------------------------------------

router.get(
    "/employees",

    permissionMiddleware(
        "Attendance",
        "Full"
    ),

    controller.employees
);

// ------------------------------------------------------
// Store filter data
// ------------------------------------------------------

router.get(
    "/stores",

    permissionMiddleware(
        "Attendance",
        "Full"
    ),

    controller.stores
);

// ======================================================
// DELETE ALL
// ======================================================
//
// IMPORTANT:
// This route MUST appear before /:id.
//
// Otherwise:
//     /delete-all
//
// could be interpreted as:
//     /:id
//
// ------------------------------------------------------

router.delete(
    "/delete-all",

    permissionMiddleware(
        "Attendance",
        "Full"
    ),

    controller.deleteAll
);

// ======================================================
// DELETE SINGLE ATTENDANCE RECORD
// ======================================================

router.delete(
    "/:id",

    permissionMiddleware(
        "Attendance",
        "Full"
    ),

    controller.deleteRecord
);

// ======================================================
// EXPORT
// ======================================================

module.exports = router;