const express = require("express");
const router = express.Router();

// ======================================================
// MIDDLEWARE
// ======================================================

// Attendance is loaded with lazy dependencies so a startup-time problem in
// database/gallery/notification modules cannot silently prevent the entire
// /api/attendance router from mounting and turn every report request into a
// generic 404. Dependencies are loaded when the specific endpoint is used.
const lazy = (loader) => (req, res, next) => {
    try {
        const middleware = loader();
        if (typeof middleware !== "function") {
            throw new Error("Attendance dependency did not return middleware");
        }
        return middleware(req, res, next);
    } catch (error) {
        console.error("Attendance dependency load error:", error);
        return res.status(503).json({
            success: false,
            message: "Attendance service is temporarily unavailable.",
            requestId: req.requestId
        });
    }
};

const auth = lazy(() => require("../middleware/authMiddleware"));
const permission = (moduleName, requiredPermission) =>
    lazy(() => require("../middleware/permissionMiddleware")(moduleName, requiredPermission));
const controller = (method) =>
    lazy(() => require("../controllers/attendanceController")[method]);

const createUploadMiddleware = () => {
    const multer = require("multer");
    const fs = require("fs");
    const path = require("path");
    const { UPLOAD_DIR } = require("../config/storage");

    const uploadDir = path.join(UPLOAD_DIR, "attendance");
    fs.mkdirSync(uploadDir, { recursive: true });

    const storage = multer.diskStorage({
        destination: (_req, _file, cb) => cb(null, uploadDir),
        filename: (_req, file, cb) => {
            const ext = path.extname(file.originalname || ".jpg").toLowerCase() || ".jpg";
            const uniqueName =
                `attendance-${Date.now()}-${Math.random().toString(36).slice(2, 9)}${ext}`;
            cb(null, uniqueName);
        }
    });

    return multer({
        storage,
        limits: { fileSize: 5 * 1024 * 1024 },
        fileFilter: (_req, file, cb) => {
            if (/^image\/(jpeg|png|webp)$/i.test(file.mimetype)) {
                return cb(null, true);
            }
            return cb(new Error("Only JPG, PNG or WEBP attendance photos are allowed."));
        }
    }).single("photo");
};

const upload = lazy(createUploadMiddleware);
const syncGalleryAttachment = (fieldName) =>
    lazy(() => require("../middleware/galleryAttachmentSync")("Attendance", fieldName));

// ======================================================
// AUTHENTICATION
// ======================================================

router.use(auth);

// ======================================================
// EMPLOYEE ATTENDANCE WORKSPACE
// ======================================================

// ------------------------------------------------------
// Load employee attendance context
// ------------------------------------------------------

router.get(
    "/context",
    controller("context")
);

// ------------------------------------------------------
// Check-in
//
// Photo is automatically captured by the frontend.
// GPS is validated by the controller.
// Store is determined by the backend.
// Timestamp is generated by attendanceModel.
// ------------------------------------------------------

router.post(
    "/check-in",
    upload,
    syncGalleryAttachment("check-in-photo"),
    controller("checkIn")
);

// ------------------------------------------------------
// Check-out
//
// A fresh automatic photo is required.
// GPS is validated by the controller.
// Timestamp is generated by attendanceModel.
// ------------------------------------------------------

router.post(
    "/check-out",
    upload,
    syncGalleryAttachment("check-out-photo"),
    controller("checkOut")
);

// ======================================================
// ATTENDANCE MANAGEMENT
// ======================================================
//
// Only:
//   Administrator
//   OR
//   Attendance = Full
//
// can access these endpoints.
// ======================================================

// ------------------------------------------------------
// Attendance photo access token
// ------------------------------------------------------

router.get(
    "/photo-token",

    permission(
        "Attendance",
        "Full"
    ),

    controller("photoToken")
);

// Stream the database-backed Gallery copy using Attendance permissions.
router.get(
    "/photo/:id/:type",

    permission(
        "Attendance",
        "Full"
    ),

    controller("serveAttendancePhoto")
);

// ------------------------------------------------------
// Reports
// ------------------------------------------------------

router.get(
    "/reports",

    permission(
        "Attendance",
        "Full"
    ),

    controller("reports")
);

// ------------------------------------------------------
// Employee filter data
// ------------------------------------------------------

router.get(
    "/employees",

    permission(
        "Attendance",
        "Full"
    ),

    controller("employees")
);

// ------------------------------------------------------
// Store filter data
// ------------------------------------------------------

router.get(
    "/stores",

    permission(
        "Attendance",
        "Full"
    ),

    controller("stores")
);

// ======================================================
// DELETE ALL
// ======================================================
//
// IMPORTANT:
// This route MUST appear before /:id.
//
// Otherwise:
//     /delete-all
//
// could be interpreted as:
//     /:id
//
// ------------------------------------------------------

router.delete(
    "/delete-all",

    permission(
        "Attendance",
        "Full"
    ),

    controller("deleteAll")
);

// ======================================================
// DELETE SINGLE ATTENDANCE RECORD
// ======================================================

router.delete(
    "/:id",

    permission(
        "Attendance",
        "Full"
    ),

    controller("deleteRecord")
);

// ======================================================
// EXPORT
// ======================================================

module.exports = router;