const db = require("../config/db");

// ======================================================
// CHECKLIST COMPLIANCE (Store submission tracker)
// GET /api/checklist-reports/compliance
//
// Query params (all optional):
//   start_date, end_date   YYYY-MM-DD (defaults to today)
//   checklist_type_id      limit to one checklist type
//   store_id               limit to one store
//
// Answers, per date range:
//   - how many stores submitted a checklist / how many did not
//   - how many checklist submissions (reports) were generated
//   - how many action points those submissions generated
//   - per store: total submissions, days submitted, most in one
//     day, a per-day breakdown, action points and average score.
//
// A store that submits twice is still ONE submitted store; the
// extra submissions are counted in `submissions` / `per_day`.
// ======================================================

const DATE_RE = /^\d{4}-\d{2}-\d{2}$/;

const todayLocal = () => {
    const now = new Date();
    const pad = (n) => String(n).padStart(2, "0");
    return `${now.getFullYear()}-${pad(now.getMonth() + 1)}-${pad(now.getDate())}`;
};

const toDateKey = (value) => {
    if (!value) return null;
    if (value instanceof Date) {
        const pad = (n) => String(n).padStart(2, "0");
        return `${value.getFullYear()}-${pad(value.getMonth() + 1)}-${pad(value.getDate())}`;
    }
    return String(value).slice(0, 10);
};

const daysBetween = (start, end) => {
    const a = new Date(`${start}T00:00:00`);
    const b = new Date(`${end}T00:00:00`);
    return Math.max(1, Math.round((b - a) / 86400000) + 1);
};

exports.getChecklistCompliance = async (req, res) => {
    try {
        let startDate = DATE_RE.test(req.query.start_date || "") ? req.query.start_date : null;
        let endDate = DATE_RE.test(req.query.end_date || "") ? req.query.end_date : null;

        if (!startDate && !endDate) {
            startDate = todayLocal();
            endDate = startDate;
        } else if (!startDate) {
            startDate = endDate;
        } else if (!endDate) {
            endDate = startDate;
        }

        if (startDate > endDate) {
            [startDate, endDate] = [endDate, startDate];
        }

        const checklistTypeId = Number(req.query.checklist_type_id) || null;
        const storeId = Number(req.query.store_id) || null;

        // ---------- shared submission filter ----------
        let subWhere = "WHERE DATE(cs.submission_date) BETWEEN ? AND ?";
        const subParams = [startDate, endDate];

        if (checklistTypeId) {
            subWhere += " AND cs.checklist_type_id = ?";
            subParams.push(checklistTypeId);
        }
        if (storeId) {
            subWhere += " AND cs.store_id = ?";
            subParams.push(storeId);
        }

        // ---------- stores in scope ----------
        // Active stores, plus any inactive store that still submitted
        // in the selected range (so nothing submitted is ever hidden).
        let storeSql = `
            SELECT s.id, s.store_name, s.store_code, s.city, s.state, s.status
            FROM stores s
            WHERE (
                COALESCE(LOWER(s.status), 'active') = 'active'
                OR s.id IN (SELECT DISTINCT cs.store_id FROM checklist_submissions cs ${subWhere})
            )
        `;
        const storeParams = [...subParams];
        if (storeId) {
            storeSql += " AND s.id = ?";
            storeParams.push(storeId);
        }
        storeSql += " ORDER BY s.store_name ASC";

        // ---------- submissions per store per day ----------
        const perDaySql = `
            SELECT
                cs.store_id,
                DATE_FORMAT(cs.submission_date, '%Y-%m-%d') AS day,
                COUNT(*) AS submissions
            FROM checklist_submissions cs
            ${subWhere}
            GROUP BY cs.store_id, DATE_FORMAT(cs.submission_date, '%Y-%m-%d')
        `;

        // ---------- per store totals ----------
        const perStoreSql = `
            SELECT
                cs.store_id,
                COUNT(*) AS submissions,
                AVG(cs.inspection_score) AS average_score,
                MIN(cs.submission_date) AS first_submission,
                MAX(cs.submission_date) AS last_submission,
                GROUP_CONCAT(DISTINCT COALESCE(u.name, cs.submitted_by_name) SEPARATOR ', ') AS submitted_by,
                GROUP_CONCAT(DISTINCT ct.checklist_name ORDER BY ct.checklist_name SEPARATOR ', ') AS checklist_types
            FROM checklist_submissions cs
            LEFT JOIN users u ON u.id = cs.submitted_by
            LEFT JOIN checklist_types ct ON ct.id = cs.checklist_type_id
            ${subWhere}
            GROUP BY cs.store_id
        `;

        // ---------- action points generated by those submissions ----------
        const actionSql = `
            SELECT
                cs.store_id,
                COUNT(DISTINCT ap.id) AS action_points,
                COUNT(DISTINCT CASE WHEN LOWER(COALESCE(ap.status, 'Open')) = 'closed' THEN ap.id END) AS action_closed
            FROM action_points ap
            LEFT JOIN checklist_submission_answers csa ON csa.id = ap.submission_answer_id
            INNER JOIN checklist_submissions cs ON cs.id = COALESCE(ap.submission_id, csa.submission_id)
            ${subWhere}
            GROUP BY cs.store_id
        `;

        const [stores, perDay, perStore, actions] = await Promise.all([
            db.query(storeSql, storeParams),
            db.query(perDaySql, subParams),
            db.query(perStoreSql, subParams),
            db.query(actionSql, subParams),
        ]);

        const unwrap = (r) => (Array.isArray(r) && Array.isArray(r[0]) ? r[0] : r) || [];
        const storeRows = unwrap(stores);
        const dayRows = unwrap(perDay);
        const totalRows = unwrap(perStore);
        const actionRows = unwrap(actions);

        const dayMap = new Map();
        const trendMap = new Map();
        dayRows.forEach((row) => {
            const key = Number(row.store_id);
            const day = toDateKey(row.day);
            const count = Number(row.submissions || 0);
            if (!dayMap.has(key)) dayMap.set(key, []);
            dayMap.get(key).push({ date: day, submissions: count });

            const t = trendMap.get(day) || { date: day, stores: 0, submissions: 0 };
            t.stores += 1;
            t.submissions += count;
            trendMap.set(day, t);
        });

        const totalMap = new Map(totalRows.map((r) => [Number(r.store_id), r]));
        const actionMap = new Map(actionRows.map((r) => [Number(r.store_id), r]));

        const rows = storeRows.map((store) => {
            const id = Number(store.id);
            const totals = totalMap.get(id);
            const ap = actionMap.get(id);
            const days = (dayMap.get(id) || []).sort((a, b) => b.date.localeCompare(a.date));
            const submissions = Number(totals?.submissions || 0);

            return {
                store_id: id,
                store_name: store.store_name,
                store_code: store.store_code,
                city: store.city,
                state: store.state,
                store_status: store.status || "Active",
                submitted: submissions > 0,
                submissions,
                days_submitted: days.length,
                max_per_day: days.reduce((m, d) => Math.max(m, d.submissions), 0),
                multiple_in_a_day: days.some((d) => d.submissions > 1),
                per_day: days,
                first_submission: totals?.first_submission || null,
                last_submission: totals?.last_submission || null,
                submitted_by: totals?.submitted_by || "",
                checklist_types: totals?.checklist_types || "",
                average_score: totals?.average_score == null
                    ? null
                    : Number(Number(totals.average_score).toFixed(1)),
                action_points: Number(ap?.action_points || 0),
                action_closed: Number(ap?.action_closed || 0),
            };
        });

        const submittedStores = rows.filter((r) => r.submitted).length;
        const totalStores = rows.length;
        const totalSubmissions = rows.reduce((s, r) => s + r.submissions, 0);
        const totalActions = rows.reduce((s, r) => s + r.action_points, 0);
        const closedActions = rows.reduce((s, r) => s + r.action_closed, 0);
        const multiStores = rows.filter((r) => r.multiple_in_a_day).length;
        const scored = rows.filter((r) => r.average_score != null);

        return res.json({
            success: true,
            data: {
                range: {
                    start_date: startDate,
                    end_date: endDate,
                    days: daysBetween(startDate, endDate),
                },
                summary: {
                    total_stores: totalStores,
                    submitted_stores: submittedStores,
                    not_submitted_stores: totalStores - submittedStores,
                    compliance_rate: totalStores
                        ? Number(((submittedStores / totalStores) * 100).toFixed(1))
                        : 0,
                    total_submissions: totalSubmissions,
                    reports_generated: totalSubmissions,
                    repeat_submissions: Math.max(0, totalSubmissions - rows.reduce((s, r) => s + r.days_submitted, 0)),
                    multiple_in_a_day_stores: multiStores,
                    action_points: totalActions,
                    action_points_closed: closedActions,
                    action_points_open: totalActions - closedActions,
                    average_score: scored.length
                        ? Number((scored.reduce((s, r) => s + r.average_score, 0) / scored.length).toFixed(1))
                        : null,
                },
                trend: [...trendMap.values()].sort((a, b) => a.date.localeCompare(b.date)),
                stores: rows,
            },
        });
    } catch (error) {
        console.error("CHECKLIST COMPLIANCE ERROR:", error);
        return res.status(500).json({
            success: false,
            message: "Unable to load checklist store compliance.",
        });
    }
};
