const XLSX=require("xlsx");const fs=require("fs");const Inventory=require("../models/inventoryPlanningModel");const {logActivity}=require("../utils/activityLogger");
const norm=h=>String(h||"").toLowerCase().replace(/[^a-z0-9]/g,"");
const aliases={store_name:["storename","store","outlet","shop"],store_id:["storeid"],sale_year:["year","saleyear","fiscalyear"],sale_month:["month","salemonth","period"],category:["category","categoryname","productcategory"],sales_amount:["sales","salesamount","revenue","netsales"],units_sold:["units","unitssold","quantity","qty","salesunits"],discount_percent:["discount","discountpercent","discountpercentage"]};
function parseFile(path){const wb=XLSX.readFile(path,{cellDates:true});const sh=wb.Sheets[wb.SheetNames[0]];const raw=XLSX.utils.sheet_to_json(sh,{defval:""});if(!raw.length)throw new Error("The uploaded file is empty.");const headers=Object.keys(raw[0]);const map={};for(const [key,list] of Object.entries(aliases)){const idx=headers.map(norm).findIndex(h=>list.includes(h));map[key]=idx>=0?headers[idx]:null;}const required=["store_name","sale_year","sale_month","category","sales_amount","units_sold"];const missing=required.filter(k=>!map[k]);if(missing.length)throw new Error(`Missing required columns: ${missing.join(", ")}.`);return raw.map((row,i)=>{const d={store_id:map.store_id?Number(row[map.store_id])||null:null,store_name:String(row[map.store_name]||"").trim(),sale_year:Number(row[map.sale_year]),sale_month:Inventory.normalizeMonth(row[map.sale_month]),category:String(row[map.category]||"").trim(),sales_amount:Inventory.normalizeNumber(row[map.sales_amount]),units_sold:Inventory.normalizeNumber(row[map.units_sold]),discount_percent:map.discount_percent?Inventory.normalizeNumber(row[map.discount_percent]):0};if(!d.store_name||!d.category||!Number.isInteger(d.sale_year)||!d.sale_month)throw new Error(`Invalid data on row ${i+2}. Store, year, month and category are required.`);return d;});}
exports.getSales=async(req,res)=>{try{const d=await Inventory.listSales(req.query);res.json({success:true,data:d.rows,pagination:{page:d.page,pageSize:d.pageSize,total:d.total}});}catch(e){console.error(e);res.status(500).json({success:false,message:"Unable to load ERP historical sales data."});}};
exports.getSaleById=async(req,res)=>{try{const d=await Inventory.getSalesById(req.params.id);if(!d)return res.status(404).json({success:false,message:"ERP sales record not found."});res.json({success:true,data:d});}catch(e){res.status(500).json({success:false,message:"Unable to load ERP sales record."});}};
exports.createSale=async(req,res)=>{try{const b=req.body||{};if(!b.store_name?.trim()||!b.category?.trim()||!b.sale_year||!b.sale_month)return res.status(400).json({success:false,message:"Store, year, month and category are required."});const id=await Inventory.createSale({...b,created_by:req.user.id});logActivity({activity_type:"Inventory Planning",reference_id:id,title:"ERP Sales Record Added",description:`${b.store_name} ${b.category} sales record was added`,module_name:"Inventory Planning",status:"Open",priority:"Medium",created_by:req.user.id,assigned_to:null});res.status(201).json({success:true,id,message:"ERP sales record added successfully."});}catch(e){console.error(e);res.status(500).json({success:false,message:"Unable to create ERP sales record."});}};
exports.deleteSale=async(req,res)=>{try{await Inventory.deleteSale(req.params.id);res.json({success:true,message:"ERP sales record deleted successfully."});}catch(e){res.status(500).json({success:false,message:"Unable to delete ERP sales record."});}};
exports.deleteAllSales=async(req,res)=>{try{await Inventory.deleteAllSales();res.json({success:true,message:"All ERP historical sales data deleted successfully."});}catch(e){res.status(500).json({success:false,message:"Unable to delete ERP historical sales data."});}};
exports.exportSales=async(req,res)=>{try{res.json({success:true,data:await Inventory.exportSales()});}catch(e){res.status(500).json({success:false,message:"Unable to export ERP sales data."});}};
exports.bulkUploadSales=async(req,res)=>{if(!req.file)return res.status(400).json({success:false,message:"Please select a CSV or Excel file."});try{const rows=parseFile(req.file.path);const inserted=await Inventory.bulkInsertSales(rows,req.user.id);res.status(201).json({success:true,inserted,message:`${inserted} historical sales records imported successfully.`});}catch(e){console.error(e);res.status(400).json({success:false,message:e.message||"Bulk upload failed."});}finally{fs.unlink(req.file.path,()=>{});}};
exports.getOptions=async(req,res)=>{try{res.json({success:true,data:await Inventory.getOptions()});}catch(e){res.status(500).json({success:false,message:"Unable to load inventory planning options."});}};
exports.analyze=async(req,res)=>{try{res.json({success:true,data:await Inventory.analyze(req.body||{})});}catch(e){res.status(400).json({success:false,message:e.message||"Unable to analyze inventory data."});}};
exports.savePlan=async(req,res)=>{try{const b=req.body||{};if(!b.planningMonth||!b.planningYear||!Array.isArray(b.storeIds)||!b.storeIds.length)return res.status(400).json({success:false,message:"Planning month, year and at least one store are required."});const id=await Inventory.savePlan(b,req.user.id);logActivity({activity_type:"Inventory Planning",reference_id:id,title:"Inventory Plan Saved",description:`Inventory plan saved for ${b.planningMonth} ${b.planningYear}`,module_name:"Inventory Planning",status:"Open",priority:"Medium",created_by:req.user.id,assigned_to:null});res.status(201).json({success:true,id,message:"Inventory plan saved successfully."});}catch(e){console.error(e);res.status(500).json({success:false,message:"Unable to save inventory plan."});}};
exports.getPlans=async(req,res)=>{try{res.json({success:true,data:await Inventory.listPlans()});}catch(e){res.status(500).json({success:false,message:"Unable to load saved inventory plans."});}};
exports.getPlan=async(req,res)=>{try{const d=await Inventory.getPlan(req.params.id);if(!d)return res.status(404).json({success:false,message:"Inventory plan not found."});res.json({success:true,data:d});}catch(e){res.status(500).json({success:false,message:"Unable to load inventory plan."});}};
exports.deletePlan=async(req,res)=>{try{await Inventory.deletePlan(req.params.id);res.json({success:true,message:"Inventory plan deleted successfully."});}catch(e){res.status(500).json({success:false,message:"Unable to delete inventory plan."});}};
exports.deleteAllPlans=async(req,res)=>{try{await Inventory.deleteAllPlans();res.json({success:true,message:"All saved inventory plans deleted successfully."});}catch(e){res.status(500).json({success:false,message:"Unable to delete saved inventory plans."});}};
exports.exportPlans=async(req,res)=>{try{res.json({success:true,data:await Inventory.exportPlans()});}catch(e){res.status(500).json({success:false,message:"Unable to export inventory plans."});}};
